s=open('make_cover.py',encoding='utf-8').read()
s=s.replace(" 'B': ["," 'D': [('육아휴직 12개월', 124, Wt, 't'), ('2,310|만원', 250, Y, 'num'), ('상한에 걸리면 똑같아요', 92, Wt, 't')],\n 'E': [('육아휴직 12개월', 124, '#1F2937', 't'), ('2,310|만원', 250, '#E8590C', 'num'), ('상한에 걸리면 똑같아요', 92, '#1F2937', 't')],\n 'B': [")
s=s.replace("v = sys.argv[1]","v = sys.argv[1]\nif v=='E': MC.HTML = MC.HTML.replace('background:#0F1B3D','background:#FFF1D6').replace('color:#A5B4D4','color:#6B7280')")
s=s.replace("['2,310', '150'] if v=='B' else ['2,310']","['2,310', '150'] if v=='B' else ['2,310']")
open('make_cover.py','w',encoding='utf-8').write(s)
j=open('judge_cover.py',encoding='utf-8').read().replace("for k in 'C':","for k in 'DE':")
open('judge_cover.py','w',encoding='utf-8').write(j)
r=open('judge_run.py',encoding='utf-8').read().replace("jobs=[('C',os.path.join(HH,'covers_try','board_C.png'),os.path.join(HH,'pkg')),","jobs=[('D',os.path.join(HH,'covers_try','board_D.png'),os.path.join(HH,'pkg')),('E',os.path.join(HH,'covers_try','board_E.png'),os.path.join(HH,'pkg')),").replace("_C.md","_DE.md").replace("_C.json","_DE.json")
open('judge_run.py','w',encoding='utf-8').write(r)
